### ISSUE TITLE
Error: 'charmap' codec can't decode byte 0x8f in position 156

### ISSUE THREAD

**Issue by minggangw** [ros2/rosidl#388] opened 2019-06-16 11:44 UTC
## Bug report

**Required Info:**

- Operating System:
  - Windows 10 ONLY
- Installation type:
  - Binary of nightly build (http://ci.ros2.org/view/packaging/job/packaging_windows/lastSuccessfulBuild/artifact/ws/ros2-package-windows-AMD64.zip)
- Version or commit hash:
- DDS implementation:
- Client library (if applicable):

#### Steps to reproduce issue

Pass the path of [WStrings.msg](https://github.com/ros2/test_interface_files/blob/master/msg/WStrings.msg) as the parameter of Python method [parse_message_file](https://github.com/ros2/rosidl/blob/ced307012bda3413d6c495914bf517d0d03748f1/rosidl_adapter/rosidl_adapter/parser.py#L427)

#### Expected behavior
Execute successfully
#### Actual behavior
Error: 'charmap' codec can't decode byte 0x8f in position 156: character maps to <undefined>
#### Additional information
- Python version: Python3.7 x64
- Suspection: there are some special characters though commented out, and I found possible some potential reason, see https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character

Thanks!

**Comment by dirk-thomas** [comment] 2019-07-18 20:15
I misread the description and comments and assumed the problem was in generated C / C++ code.

Since this actually happens when reading the interface file I think #390 should be sufficient to resolve your problem. @minggangw please comment here if it addressed your problem.

**Comment by dirk-thomas** [comment] 2019-07-19 16:21
Reopening since there are follow up issues when using non-ASCII character in e.g. default values:
* ros2/test_interface_files#8 adds a message with non-ASCII characters in the default values

**Comment by dirk-thomas** [comment] 2019-07-26 05:22
With all PRs rebased to address other unrelated test failures I triggered an full round of CI builds to double check for regressions:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7670)](http://ci.ros2.org/job/ci_linux/7670/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3778)](http://ci.ros2.org/job/ci_linux-aarch64/3778/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6275)](http://ci.ros2.org/job/ci_osx/6275/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7513)](http://ci.ros2.org/job/ci_windows/7513/)

**Comment by minggangw** [comment] 2019-07-30 08:41
This problem is fixed, I verified it on https://ci.appveyor.com/project/minggangw/rclnodejs/builds/26335124, thanks!

**Comment by dirk-thomas** [comment] 2019-07-30 15:29
Until the list of pending PRs is merged we will keep this ticket open.

**Comment by dirk-thomas** [comment] 2019-07-30 19:52
I disabled one case which doesn't seem to work cross vendor: https://github.com/ros2/system_tests/pull/377/commits/5d100b64178f679cd436772ca2258532d7389126

Hopefully the final round of CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7729)](http://ci.ros2.org/job/ci_linux/7729/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3833)](http://ci.ros2.org/job/ci_linux-aarch64/3833/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6328)](http://ci.ros2.org/job/ci_osx/6328/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7589)](http://ci.ros2.org/job/ci_windows/7589/)

**Closed** 2019-07-31 14:39 UTC
Labels: bug
